import type { Project } from '../lib/markdown'

const articleMarkdown = [
  '# Storybook Artikel-Demo',
  'Ein einleitender Absatz mit **fetter Schrift**, *kursivem Text* und [einem Link](https://example.com).',
  '',
  '## Typografie und Listen',
  '### Subheadline',
  'Dieser Absatz zeigt das normale Markdown-Textverhalten im Artikel.',
  '',
  '- Strategie',
  '- Design',
  '- Entwicklung',
  '',
  '```list style="plain" split="count" splitAfter="4"',
  '- Discovery',
  '- UX Audit',
  '- Wireframes',
  '- Visual Design',
  '- Prototyping',
  '- Handoff',
  '```',
  '',
  '```callout type="insight" title="Wichtiger Hinweis"',
  'Dieser Block wird als **Callout** mit Accent-Farbe gerendert.',
  '```',
  '',
  '```small',
  'Das ist ein Small-Text Block fuer Meta-Informationen.',
  '```',
  '',
  '```palette title="Brand Palette" description="Farbsystem aus dem Artikel"',
  'name="Midnight" hex="#1C1D20" usage="Background" rank=1',
  'name="Sky" hex="#3DB1FF" usage="Primary Accent" rank=2',
  'name="Mint" hex="#8AE9C1" usage="Secondary Accent" rank=3',
  'name="Cloud" hex="#F5F5F7" usage="Surface" rank=4',
  'name="Ink" hex="#111827" usage="Text" rank=5',
  '```',
  '',
  '```ts title="Code Example" filename="demo.ts"',
  'export const sum = (a: number, b: number) => a + b',
  '```',
  '',
  '```stats',
  '7+::Years Experience',
  '200+::Projects Delivered',
  '8::Awards',
  '```',
  '',
  '![Galerie](/assets/rk-1.png|/assets/rk-2.png::Alternative Ansicht)',
  '',
  '[video](/assets/book.mp4|/assets/book.avif)',
  '',
  '```font name="Inter" styles="Regular, Medium, Bold" sample="Design that ships."',
  '```',
  '',
  '```mockup type="iphone" image="/assets/reminders-plus/IMG_3086.PNG"',
  '```',
  '',
  '```safari-tab image="/assets/einvoice/01.png" url="example.com"',
  '```',
  '',
  '```lottie path="/assets/sample-lottie.json" loop=true',
  '```',
  '',
  '```three height="420px" preset="city"',
  '```',
  '',
  '```animation-sequence videoPath="/assets/reminders-8.mp4" mobileVideoPath="/assets/reminders-8-mobile-scrub.mp4" safariVideoPath="/assets/reminders-8-safari-scrub.mp4" frameCount=501',
  '```',
  '',
  '```reveal',
  'Dieser Satz demonstriert den Reveal-Block im Markdown.',
  '```',
  '',
  '[projects:storybook-related-1,storybook-related-2]',
].join('\n')

const baseProject: Project = {
  id: 1,
  title: 'Reminders Plus',
  subtitle: 'Produktivitaet mit smarter Routine',
  slug: 'storybook-article',
  category: ['ux/ui', 'development'],
  client: ['Demo Client'],
  collaboration: [{ 'Demo Designer': 'https://example.com' }],
  awards: ['Honorable Mention'],
  type: ['case study'],
  excerpts: 'Case Study fuer Storybook-Komponenten und Markdown-Elemente.',
  published: '2026-02-10',
  description: 'Storybook-Fixture-Daten fuer Komponenten und Artikel.',
  bgColor: '#3DB1FF',
  image: '/assets/reminders-plus/reminders-promo.jpg',
  video: '/assets/reminders-7.mp4',
  pageVideo: '/assets/reminders-8.mp4',
  heroImage: '/assets/reminders-plus/landing.png',
  heroLottie: '/assets/sample-lottie.json',
  hasAnimation: true,
  animationSequence: {
    videoPath: '/assets/reminders-8.mp4',
    mobileVideoPath: '/assets/reminders-8-mobile-scrub.mp4',
    safariVideoPath: '/assets/reminders-8-safari-scrub.mp4',
    frameCount: 501,
  },
  featured: true,
  content: articleMarkdown,
}

export const sampleProject: Project = baseProject

export const sampleProjects: Project[] = [
  baseProject,
  {
    ...baseProject,
    id: 2,
    title: 'E-Invoice Platform',
    subtitle: 'Enterprise UX und Content-System',
    slug: 'storybook-related-1',
    excerpts: 'Skalierbares Interface fuer Rechnungsprozesse.',
    published: '2025-12-20',
    bgColor: '#0EA5E9',
    image: '/assets/einvoice/hero.jpg',
    heroImage: '/assets/einvoice/hero.jpg',
    featured: false,
    hasAnimation: false,
    animationSequence: undefined,
    heroLottie: undefined,
    content:
      '# E-Invoice\nKurztext fuer eine verlinkte Referenzkarte im Artikel.',
  },
  {
    ...baseProject,
    id: 3,
    title: 'Berlin Lawyers Relaunch',
    subtitle: 'Brand, Web und Performance',
    slug: 'storybook-related-2',
    excerpts: 'Neues visuelles System und moderne Website.',
    published: '2025-08-11',
    bgColor: '#22C55E',
    image: '/assets/rk.webp',
    heroImage: '/assets/rk.webp',
    featured: false,
    hasAnimation: false,
    animationSequence: undefined,
    heroLottie: undefined,
    content: '# Relaunch\nKurztext fuer die zweite Referenzkarte im Artikel.',
  },
  {
    ...baseProject,
    id: 4,
    title: 'Earth Week Campaign',
    subtitle: 'Motion-first Storytelling',
    slug: 'storybook-related-3',
    excerpts: 'Cross-platform Kampagne mit Video-Assets.',
    published: '2025-06-03',
    bgColor: '#6366F1',
    image: '/assets/earthweek-01.jpg',
    heroImage: '/assets/earthweek-01.jpg',
    featured: true,
    content: '# Earth Week\nBeispielprojekt fuer Karussell und Work-Section.',
  },
]

export const sampleArticleProject: Project = {
  ...sampleProject,
  content: articleMarkdown,
}

